name: vaam_khanegi
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^2.1.4
  get: ^4.1.4
  get_it: ^6.0.0
  http: ^0.13.3
  intl: ^0.17.0
  persian_fonts: ^1.0.3
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  top_snackbar_flutter: ^1.0.0


 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/giah.jpg
    


 
  

 
